version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/demo-app

hooks:
  AfterInstall:
    - location: deploy/install.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: ec2-user

  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 300
      runas: ec2-user
