version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - nvm install 20
      - node -v
      - npm -v
      - echo Installing backend dependencies...
      - cd backend
      - npm install

  build:
    commands:
      - echo Build step skipped

artifacts:
  files:
    - '**/*'
