version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js...
      - n 20
      - npm install

  pre_build:
    commands:
      - echo Checking Node version...
      - node -v

  build:
    commands:
      - echo Building project...
      - echo No separate build step needed for Node backend

  post_build:
    commands:
      - echo Build completed successfully

artifacts:
  files:
    - '**/*'
  discard-paths: no
