version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install

  pre_build:
    commands:
      - echo Node version:
      - node -v

  build:
    commands:
      - echo No build step needed for Node backend

  post_build:
    commands:
      - echo Zipping application...
      - zip -r app.zip . -x "*.git*"

artifacts:
  files:
    - app.zip
